_default =                "conda,wheel,sdist,nixpkgs"

gdal =                    "nixpkgs"
pip =                     "nixpkgs,sdist"
setupmeta =               "wheel"
setuptools =              "nixpkgs"
wheel =                   "nixpkgs,sdist"